### ISSUE TITLE
Cannot be compiled on modern Ubuntu versions

### ISSUE THREAD

**Issue by ImperatorStorm** [SiegeEngineers/auto-mods#1]
`genieutils/CMakeLists.txt` requires libiconv-dev, however this library doesn't exist on modern Ubuntu versions, as libiconv-dev has since been merged with libc6-dev. CMake doesn't recognize the libiconv-dev section of libc6-dev, causing compile to fail with error 
```
CMake Error at genieutils/CMakeLists.txt:19 (find_library):
  Could not find iconv using the following names:


-- Configuring incomplete, errors occurred!
See also "/media/imperatorstorm/Storage/auto-mods/build/CMakeFiles/CMakeOutput.log".

**Comment by ImperatorStorm** [comment]
can be fixed by removing `find_library(Iconv REQUIRED)` from genieutils/CMakeLists.txt

**Comment by FranciscoDA** [comment]
You should be able to compile without dropping iconv support by updating the cmake syntax like so:

https://github.com/SiegeEngineers/auto-mods/pull/3/files#diff-e26045e6f265fbe8cf766e780ded06d6455dcbc1af67e9feed97149a68a8cfb9R15

**Comment by simonsan** [comment]
Modern CMake can detect it and sets `Iconv_IS_BUILT_IN`:

https://cmake.org/cmake/help/latest/module/FindIconv.html

**Comment by simonsan** [comment]
```
sed -i 's/find_library(iconv REQUIRED)/find_package(Iconv REQUIRED)/' genieutils/CMakeLists.txt
```

Should fix it.

**Comment by simonsan** [comment]
Tracking https://github.com/Tapsa/genieutils/pull/3

**Comment by simonsan** [comment]
@ImperatorStorm Can you check again, but I think this should be fine now.

**Comment by ImperatorStorm** [comment]
it indeed works, thanks
