### ISSUE TITLE
Random cost mod discussion

### ISSUE THREAD

**Issue by HSZemi** [SiegeEngineers/auto-mods#14]
@HSZemi thanks for the feedback!  I have a couple of questions and notes.

My friends and I discovered the random mod a few weeks ago and have been avid fans.  For the first few games, it was fun every time, but after a couple days we quickly noticed that most of random mod games had devolved into one or both of these two fairly predictable metas:

1. **Castles are cheap.**  Castles are normally 650 stone, so in the random mod if they are significantly cheaper (they almost always are) the game devolves to castle spam around your base with a race to a wonder.

2. **Discover spam unit with a very low cost as quickly as possible.**  In many scenarios, the random cost mod devolves into an aging up race to see who can discover a cheap spammy unit the fastest.  If someone discovers a spam unit just slightly before someone else, the game is over, as they will overrun others without time to respond.  Furthermore, the spam unit negates the need to maintain an economy, and so a major element of gameplay.

I believe random mod has a replay value problem.  Those above metas are hilarious and a joy the first few times.  After that, they become tedious and repetitive.  I think a random mod, ultimately, should give a variety of random experiences and fresh strategies to players so they always need to think on their feet, but if the random mod usually falls into two metas this is no longer the case.  I think one of the beauties of the random mod itself is that it DESTROYS the traditional AOE2 metas.  Every day, there's a new meta.  It feels fresh and new and it forces you to think out of the box, after you've been playing AOE for so long and dust has settled on your brain and you can basically play the game without thinking.

But I agree that the random mod is so fun at first that it should probably remain as it is.  I propose a new mod, something like "Random Mod Balanced" targeted with some sane defaults, like preventing castle spam and units costing 1 wood, that players can transitions into if they become fans of the default random mod and want to transition into something more nuanced. Is this something you would considering publishing through Siege Engineers if I make the code mods for it?  A lot of my friends have stopped playing Random Mod because of the metas and they said they'd be interested to come back if we there was a more balanced version that prevented those two metas I mentioned.

If not, do you mind giving me some information on how to set up a build system?  Is it a lot of work to set up?  Do ya'll have a server somewhere that publishes the new random mod every day?  Is that script in the repo here?  I don't see any devops scripts.  And how do you detect when new AOE patches go out, and thus when a new fresh dat is available for moding?  Does AOE provide an api or something for getting the fresh dat file?

Thanks for your time!

_Originally posted by @FilmCoder in https://github.com/SiegeEngineers/auto-mods/issues/12#issuecomment-779468300_

**Comment by HSZemi** [comment]
Well, that's a lot of questions. Let's see:

> Is this something you would considering publishing through Siege Engineers if I make the code mods for it?

I guess; it is not really a lot of extra work to add a fourth mod.

> do you mind giving me some information on how to set up a build system?

No.

> Is it a lot of work to set up?

Not anymore, no.

> Do ya'll have a server somewhere that publishes the new random mod every day?

Yes.

> Is that script in the repo here?

No. You are looking for [auto-mods-update](https://github.com/SiegeEngineers/auto-mods-update), which I just transferred to the SiegeEngineers organisation.

> And how do you detect when new AOE patches go out, and thus when a new fresh dat is available for moding?

I either see it on Twitter or on Discord. Then I update my local game via Steam and voilà, there is the new dat file, which I can copy onto the deployment server.

**Comment by HSZemi** [comment]
The two main "issues" with the current Random Costs Mod that I see are:

#### _Insanely_ cheap prices for units

Upgrading to Paladin for 1 wood? Whatever. Being able to create 200 Paladins for 200 wood? No bueno. Especially if you do not have access to Paladin.
Being able to create your unique unit for 1 wood? Even less bueno. Clear civ win.
There are some internal techs that cost 1 wood and some that cost 1 food. Excluding those from the randomisation fixes that issue, but then it's basically a question of if someone gets the 2 wood cost for palisades on their unique unit. That is a lot less likely to happen though.
You could of course exclude that from the randomisation as well, but I thought we had finally found a cure for quickwalling :upside_down_face: 

#### _Insanely_ expensive prices for certain core aspects of the game

- Villagers: There is a reason their cost is currently limited to 200 resources (which is quite expensive already)
- Farms: Good luck with your food economy if your farms cost more to build than they yield
- (Age advancements): Good luck getting to Feudal Age if it costs 1k wood, 2k gold and 1k stone. At least this affects all players in the same way, and is comparatively less severe for Castle and Imperial Age.
- (Houses): Good luck getting above 5 pop if your houses cost 3k resources to build. Gets mitigated by the fact that the cost changes with each age, so you often get four chances for cheap houses. Also, Town Centers and Castles are population space providing alternatives.

Cheap castles are often somewhat mitigated by the availability of cheap siege.
If you want to "fix" cheap castles by restricting their cost range, the meta _might_ just shift to the next best thing, that is Kreposts, Donjons, (Bombard) Towers.
I have already thought about checking the cost of Castles, and if it is below a certain threshold, additionally reduce their attack / number of arrows / … . But since the biggest issue seem to have been 1 wood unique units, the availability of cheap castles has not provoked many complaints yet.

What I would also like is to pair the Random Cost Mod with a language file mod that hides the cost from tooltips and the tech tree. But despite the feature [being advertised as available](https://www.ageofempires.com/news/aoe2de-update-42848/), combining data file mods with other modifications does not seem to work currently. Of course I could simply create a second mod which does that, but I mainly want to troll T90 with it as a surprise feature for community games :shrug:

**Comment by FilmCoder** [comment]
Ah ok that all makes sense, thanks for the response!  I'm going to get to work on this mod then.  All very good points you've made.

**Comment by FilmCoder** [comment]
So I've been doing some digging and I found that there are about 25 empty techs with no defined names that cost 1 wood.  I think this is why 1 wood costing units are so prevalent in the random mod, as these empty 1 wood costs are getting shuffled into the units.  Perhaps we should delete these from the pool of resources that get shuffled in, even for the main Random Mod, as this seems undesirable?

**Comment by HSZemi** [comment]
There are 37 1-wood techs, one for each civilisation.
There are also 15 1-food techs, see https://halfon.aoe2.se/

From experience, when those costs were excluded, people still kept searching for 1-wood units. Those seem to be a core part of the main mod now :shrug:

**Comment by FilmCoder** [comment]
@HSZemi ah you're right!  OK then, and that is a sound argument to keep it.  I wonder what they're used for. 37 1-wood techs with no names, for each civilization.

**Comment by HSZemi** [comment]
There is now a light version, where only prices above 5 resources get jumbled
https://mods.aoe2.se/185441
