### ISSUE TITLE
x256 mod crashes when you queue a technology after itself

### ISSUE THREAD

**Issue by Hasenn** [SiegeEngineers/auto-mods#2]
repro:
compile and make a x256 mod, (mine was with random costs) launch a game with the mod, spam click on supplies or another tech
and your game might crash (after a few tries with different techs)

**Comment by HSZemi** [comment]
Hm sorry, nothing I can do about that.
[![grafik](https://user-images.githubusercontent.com/3027817/95019228-6a02d980-0664-11eb-957c-b7188b50a253.png)](https://www.ageofempires.com/mods/details/15920/)
