### ISSUE TITLE
Burgundians - subsequent tech researches are not 33% cheaper food

### ISSUE THREAD

**Issue by Krigeris** [SiegeEngineers/auto-mods#35]
Burgundians have a civ bonus that makes economic techs cost 33% less food. Chinese have a similar bonus that reduces costs on techs. For chinese all of 9x techs are reduced. Burgundian's cost reduction however only applies to the first tech.

Whatever means of implementing the chinese tech cost reduction bonus to work for all 9x techs should be used for burgundians as well for consistency.

Also, thank you for the quick fix on the last bug report I submitted

**Comment by HSZemi** [comment]
The Chinese civ bonus modifies Resource 85 (Research Cost Modifier), whilst die Burgundian civ bonus modifies the technologies directly by their ID. This explains why for Chinese, copies of techs are also cheaper, while they are not for Burgundians.

**Comment by Krigeris** [comment]
Gotcha I did notice it with other civs so I figured that was a possibility, will close.

**Comment by Krigeris** [comment]
Gotcha I did notice it with other civs so I figured that was a possibility, will close.
