### ISSUE TITLE
[King Boom mod] Monkeys explode in Pilgrims nothing map 

### ISSUE THREAD

**Issue by TheDude-gh** [SiegeEngineers/auto-mods#40]
Since Furious Monkey Boy is part of the explosion sequence, it makes monkeys instantly explode on some random maps, notably the Pilgrim nothing, where there are three monkeys in the corner.

Maybe consider changing the last exploding unit to some other unit, which does not appear in random maps at all, like some rare hero unit.

**Comment by HSZemi** [comment]
Hilarious. I have an idea to prevent such issues in the future. Let's see when I have time to implement it

**Comment by HSZemi** [comment]
This issue should be resolved with the recent change where units for the explosion chain are not modified directly, but copied first :+1:
